### ISSUE TITLE
Correção src da imagem no Readme

### ISSUE THREAD

**Issue by Jeffgss** [HugooSantos/Search-lyrics#1]
A imagem não está aparecendo no readme pois o src contém um link que te redireciona pra página inicial do ezGif, e não para a imagem. 

<img src="https://user-images.githubusercontent.com/57115387/138322410-8747ae59-02c0-4f42-bb4f-6e0993ed684d.png" width="300px"/>

**Comment by HugooSantos** [comment]
Fixed 😁, thank you so much.
